# Generated by Django 5.2.4 on 2025-07-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('accesa', 'Luce Accesa'), ('spenta', 'Luce Spenta')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('valore_sensore', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento Luce',
                'verbose_name_plural': 'Eventi Luce',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('soglia', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Stato Corrente Luce',
                'verbose_name_plural': 'Stato Corrente Luce',
            },
        ),
    ]
