# Generated by Django 5.2.4 on 2025-07-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightevent',
            name='valore_sensore',
        ),
    ]
